site_name: Master's Grimoire
nav:
  - Home: index.md
  - Api: api/index.md
  - Web: web/index.md
  - Database: database/index.md
  - About: about.md

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - mermaid2

theme:
  name: material
mermaid:
  javascript
